### ISSUE TITLE
Agent Conversation client update bug

### ISSUE THREAD

**Issue by scm2217** [panoptyk/panoptyk-engine#13]
Right now the client is not correctly updated after leaving a conversation. The conversation items is cleared, but the agent still points to the last conversation as active.

This is likely not a controller issue as "removeAgentFromConversation" updates both the agent and conversation (and specifies to send both changes).

**Comment by mitchkm** [comment]
When updating client models, updates to a parameter being set to undefined will not be reflected in the client!
