### ISSUE TITLE
Way to validate Info predicates

### ISSUE THREAD

**Issue by scm2217** [panoptyk/panoptyk-engine#20]
We should provide a way to validate client generate Info predicates before we attempt to create them on the server. 

Right now the client user has to read Info action constructors and manually specify the action and predicate correctly. It may be worth making helper functions to generate the question request on the client before sending it to the server.

**Comment by mitchkm** [comment]
We now have the means to send question info as a payload, but validation on it is still necessary. I'll double-check the validation before I close this
