### ISSUE TITLE
Efficient way to lookup Info items based on their non-id paramters

### ISSUE THREAD

**Issue by scm2217** [panoptyk/panoptyk-engine#21]
Right now there is no efficient way to lookup Info items by their contents. This makes looking up any piece of information an O(n) task and checking Info equivalency an O(n*infoSize) task.

I propose that we find some way to generate a unique key based on the contents of an Info item (excluding owner and id). This will provide an easy way to identify all instances of a particular piece of info.

**Comment by mitchkm** [comment]
One big thing is that a lot of sorting logic will be done client-side. so it can be said to be parallelized, distributed,  and cut down from the pool of all information. Then info in question will be sent to the server so searches can come back to being O(1).

There is also the need to box info in relation to time. Something I currently am looking into. Thinking of doing a conversion of universal time (ms) into a pseudo time. This should be a one to one function that can be reversed and offset. So "day 1" can start on any real day.
