### ISSUE TITLE
This should be the Faction object not string

### ISSUE THREAD

**Issue by mitchkm** [panoptyk/panoptyk-engine#34]
https://github.com/panoptyk/panoptyk-engine/blob/68713c74a2e9331583acc2b90d80f77756524d24/src/models/information.ts#L37

**Comment by scm2217** [comment]
It is unused atm, but yes it should be changed when we eventually use faction in info.

**Comment by scm2217** [comment]
02e6e1d3709757ec248ee3d4405d16fd1c5f2b77 fixed
