### ISSUE TITLE
Clean up - refactor: place to put references before more structured issues/project are made

### ISSUE THREAD

**Issue by mitchkm** [panoptyk/panoptyk-engine#46]
This is a single point issue for the major clean up and refactors of the master branch. **POST-Thesis!** 

Resources: 
- https://medium.com/@martin_hotell/10-typescript-pro-tips-patterns-with-or-without-react-5799488d6680
- https://rmolinamir.github.io/typescript-cheatsheet/

Issues:
- [ ] Save/Load specs for all models
- [ ] `Object.assign({}, ...)` doesn't deep copy may prove to be an issue

**Comment by scm2217** [comment]
TODO:
- [ ] Modify item system to work better for gold/mass quantity resources
- [ ] Clean up the way Trading works
- [ ] Represent string statuses/tags as enums (particularly for quests)
